### ISSUE TITLE
flamegraph.py syntax error

### ISSUE THREAD

**Issue by durin42** [evanhempel/python-flamegraph#3]
https://github.com/evanhempel/python-flamegraph/blob/master/flamegraph/flamegraph.py#L90 has a string that's split over multiple lines, but this is a syntax error for me. Easy fix is probably to just add some singlequotes to use the python parser's implicit string concatenation.

**Comment by evanhempel** [comment]
Thanks for the heads up. Just pushed a fix.

I'm curious though, I never saw the syntax error with my own testing.  What python version were you using?

**Comment by durin42** [comment]
I think that was 2.6, but it might have been 3.5.
