### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by mgedmin** [evanhempel/python-flamegraph#4]
Would you mind terribly uploading python-flamegraph to PyPI?  It's a simple process:

- [sign up for an account](https://pypi.python.org/pypi?%3Aaction=register_form)
- run `python setup.py sdist register upload`
- enter the username and password when asked

(People will tell you to run [`twine upload`](https://pypi.python.org/pypi/twine) instead, because distutils do not verify SSL certificates, but I think that means you need to register the project manually via [some web form](https://pypi.python.org/pypi?%3Aaction=submit_form), instead of having `setup.py register` take care of everything.)

**Comment by evanhempel** [comment]
Thanks for the suggestion, it took me way to long to do ... but its finally up on PyPI: https://pypi.python.org/pypi/flamegraph
